---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sws-preso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sws-preso
  template:
    metadata:
      labels:
        app: k8sws-preso
    spec:
      containers:
        - name: k8sws-preso
          image: bashburn/k8sws-preso:latest
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8sws-preso
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: k8sws-preso

