hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
      metrics:
        healthSnapshot:
          intervalInMilliseconds: 100
adjective.host: http://localhost:8081
noun.host: http://localhost:8082
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
