# Contact: dave@signalfx.com
#
# 2 locations to update:
# - spec.ports.port[0]
# - DefaultAuthToken

apiVersion: v1
kind: Service
metadata:
  name: allow-smart-gateway
spec:
  type: ClusterIP
  selector:
    service: smart-gateway
  ports:
  - protocol: TCP
    port: 8081          # This is the port where you send traces from signalfx-agent
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: allow-traces-to-agent
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - name: traces-to-agent
    port: 9080
    targetPort: 9080
    protocol: TCP