# Contact: dave@signalfx.com
#
# 1 location to update:
# - spec.template.spec.containers.image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfx-smart-gateway
  labels:
    service: smart-gateway
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      service: smart-gateway
  template:
    metadata:
      labels:
        service: smart-gateway
    spec:
      containers:
      - name: smart-gateway
        image: sfx-smart-gateway
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/lib/sfproxy/etc/
            name: smart-gateway-config
      volumes:
        - name: smart-gateway-config
          configMap:
            name: smart-gateway-config
