---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: nount
    app: insult
  namespace: insult
  name: noun
spec:
  replicas: 1
  selector:
    matchLabels:
      name: noun
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: noun
        app: insult
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "8081"
        prometheus.io/metric_path: "/actuator/prometheus"
    spec:
      containers:
        - image: bashburn/noun-service:latest
          imagePullPolicy: Never
          name: noun
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SIGNALFX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: signalfx-token
                  key: access-token
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: noun
  namespace: insult
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: noun
