server:
  port: 8081
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
